gnrc_icmpv6_error: consider originator's destination address correctly
While 485dbd1fdac9c965c1f734b1dda711b35bb4ac1a (from #12175) was right
in assuming that the for most ICMPv6 error messages the originating
packet's destination address must not be a multicast, this is not the
case for _all_ ICMPv6 error messages (see [RFC 4443], section 2.4(e.3)).
Additionally, 485dbd1fdac9c965c1f734b1dda711b35bb4ac1a removed the
check for the source address ([RFC 4443], section 2.4(e.6)), which this
PR re-adds.

[RFC 4443]: https://tools.ietf.org/html/rfc4443#section-2.4